version: '3'
services:
  postgres:
    image: 'postgres:15'
    container_name: 'library_postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=library_db'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  app:
    build: ./
    container_name: 'library'
    ports:
      - "8080:8080"
